spring:
  application:
    name: ${SPRING_APPLICATION_NAME:nexora-scooby-doo}
  cloud:
    gateway:
      server:
        webmvc:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            - DedupeResponseHeader=Vary, RETAIN_FIRST
          routes:
            - id: nexora-fred
              uri: ${NEXORA_FRED}
              predicates:
                - Path=/nexora-fred/**
              filters:
                - StripPrefix=1
            - id: nexora-velma
              uri: ${NEXORA_VELMA}
              predicates:
                - Path=/nexora-velma/**
              filters:
                - StripPrefix=1
            - id: nexora-xatu
              uri: ${NEXORA_XATU}
              predicates:
                - Path=/nexora-xatu/**
              filters:
                - StripPrefix=1
            - id: nexora-bayleef
              uri: ${NEXORA_BAYLEEF}
              predicates:
                - Path=/nexora-bayleef/**
              filters:
                - StripPrefix=1
  mvc:
    log-request-details: true

server:
  port: ${PORT}
